### ISSUE TITLE
Deploying netbox on openshift 4.10

### ISSUE THREAD

**Issue by MastanaGuru** [netbox-community/netbox-chart#115]
Hi,

I am working on deploying netbox on openshift 4.10. Appreciate any help.

Created the yaml 
`helm install netbox --namespace netbox bootc/netbox --dry-run  > helm-netbox.yml`
Changed the port to 9443, the deployment goes thru fine and the all pods are up and running,  But am unable to access via the openshift route. When I change the port number to 8080 I get 
`https://netbox-netbox.apps.ocpod.bcbsnc.com/media-failure/?filename=netbox-print.css

Do I need to run nginx ?  

Appreciate any help.
Thanks
Raj

```
---
# Source: netbox/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netbox
  namespace: netbox
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: svc-certs
  labels:
    helm.sh/chart: netbox-4.1.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.2.8"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: netbox
---
# Source: netbox/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
  labels:
    helm.sh/chart: netbox-4.1.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.2.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: netbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netbox
      app.kubernetes.io/instance: netbox
      app.kubernetes.io/component: netbox
  template:
    metadata:
      annotations:
        checksum/config: a84478fa28e2d105e2efe44b41b10be782d37c749a374cd8d59dc9f0ff9f9100
        checksum/secret: 1a8d9fc7a875132ac588bb049ad5cfd48ea2010be8c5d053d918b82a6ef50aa6
      labels:
        app.kubernetes.io/name: netbox
        app.kubernetes.io/instance: netbox
        app.kubernetes.io/component: netbox
    spec:
      serviceAccountName: netbox
      # securityContext:
      #   fsGroup: 1000
      #   runAsNonRoot: true
      initContainers:
        - name: init-dirs
          image: "busybox:1.32.1"
          imagePullPolicy: IfNotPresent
          command: [/bin/sh, -c, mkdir -p /opt/unit/state /opt/unit/tmp]
          # securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #   readOnlyRootFilesystem: true
          #   runAsGroup: 1000
          #   runAsNonRoot: true
          #   runAsUser: 1000
          volumeMounts:
            - name: optunit
              mountPath: /opt/unit
      containers:
        - name: netbox
          # securityContext:
          #   capabilities:
          #     drop:
          #     - ALL
          #   readOnlyRootFilesystem: true
          #   runAsGroup: 1000
          #   runAsNonRoot: true
          #   runAsUser: 1000
          image: "netboxcommunity/netbox:v3.2.8"
          imagePullPolicy: IfNotPresent
          env:
            - name: SUPERUSER_NAME
              value: "admin"
            - name: SUPERUSER_EMAIL
              value: "admin@example.com"
            - name: SKIP_STARTUP_SCRIPTS
              value: "true"
          ports:
            - name: https
              containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /login/
          #     port: https
          #     scheme: HTTPS
          #   initialDelaySeconds: 0
          #   timeoutSeconds: 1
          #   successThreshold: 1
          #   periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/netbox/config/configuration.py
              subPath: configuration.py
              readOnly: true
            - name: config
              mountPath: /run/config/netbox
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/netbox
              readOnly: true
            - name: netbox-tmp
              mountPath: /tmp
            - name: media
              mountPath: /opt/netbox/netbox/media
              subPath: ""
            - name: optunit
              mountPath: /opt/unit
            - name: secrets
              mountPath: /run/secrets/superuser_password
              subPath: superuser_password
              readOnly: true
            - name: secrets
              mountPath: /run/secrets/superuser_api_token
              subPath: superuser_api_token
              readOnly: true
            - name: svc-certs
              mountPath: /etc/ssl/private
      volumes:
        - name: config
          configMap:
            name: netbox
        - name: svc-certs
          secret:
            secretName: svc-certs
            defaultMode: 384
            optional: false
        - name: secrets
          projected:
            sources:
              - secret:
                  name: "netbox"
                  items:
                    # Used by netbox-docker entry scripts
                    - key: superuser_password
                      path: superuser_password
                    - key: superuser_api_token
                      path: superuser_api_token
                    # Used by our configuration
                    - key: email_password
                      path: email_password
                    - key: napalm_password
                      path: napalm_password
                    - key: secret_key
                      path: secret_key
              - secret:
                  name: "netbox-postgresql"
                  items:
                    - key: "postgresql-password"
                      path: db_password
              - secret:
                  name: "netbox-redis"
                  items:
                    - key: "redis-password"
                      path: redis_tasks_password
              - secret:
                  name: "netbox-redis"
                  items:
                    - key: "redis-password"
                      path: redis_cache_password
        - name: netbox-tmp
          emptyDir:
            medium: Memory
        - name: optunit
          emptyDir:
            medium: Memory
        - name: media
          persistentVolumeClaim:
            claimName: netbox-media
---
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: netbox
  namespace: netbox
  labels:
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v3.2.8
    helm.sh/chart: netbox-4.1.1
  annotations:
    openshift.io/host.generated: 'true'
spec:
  path: /login/
  to:
    kind: Service
    name: netbox
    weight: 100
  port:
    targetPort: https
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```
