### ISSUE TITLE
Support storage config for scripts as for reports

### ISSUE THREAD

**Issue by florianschendel** [netbox-community/netbox-chart#148]
Support storage config for scripts as for reports

How it should look in the values file
```
## Storage configuration for Scripts
scriptsPersistence:
  enabled: true
  ##
  ## Existing claim to use
  existingClaim: ""
  ## Existing claim's subPath to use, e.g. "media" (optional)
  subPath: ""
  ##
.....
```

My plan is to use scripts in combination with your helm chart. I know i could also create an extra container but it make no sense for me because the Reports/Scripts are standard features of Netbox.

There is already an open issue #10.
My opinion is that the extra container solution is for special use cases.
