### ISSUE TITLE
ingress.annotations no longer working

### ISSUE THREAD

**Issue by coolhome** [netbox-community/netbox-chart#206]
Chart Version: netbox-5.0.0-beta9

Input:
```yaml
ingress:
  enabled: true
  className: azure-application-gateway
  annotations:
    "appgw.ingress.kubernetes.io/use-private-ip": "true"
    "appgw.ingress.kubernetes.io/backend-protocol": "http"
    "appgw.ingress.kubernetes.io/appgw-ssl-certificate": "some-cert"
  hosts:
    - host: netbox.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: netbox
              port:
                name: http
```

Output:
```yaml
---
# Source: netbox/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbox
  namespace: "netbox"
  labels:
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: v4.0.0
    helm.sh/chart: netbox-5.0.0-beta9
spec:
```

From testing a few variations setting `commonAnnotations` will add `ingress.annotations` but if `commonAnnotation` is default it will never add annotations to ingress.
