### ISSUE TITLE
Custom CA certificates

### ISSUE THREAD

**Issue by abctaylor** [netbox-community/netbox-chart#324]
I couldn't see a means in the Helm chart to pass in a custom CA (e.g. for calling web hooks on a LAN). Is there a method to achieve this?

A similar issue in https://github.com/netbox-community/netbox/issues/16885 has this problem too.

**Comment by hsahmed** [comment]
You can use extra volume mounts (ca-certificates.crt is the full bundle including custom certificates):
```
    extraVolumes:
      - name: ca-certificate-bundle
        configMap:
          name: ca-certificates-bundle
          defaultMode: 0644
          optional: false
          items:
          - key: ca-certificates.crt
            path: ca-certificates.crt
    extraVolumeMounts:
      - mountPath: /etc/ssl/certs/
        name: ca-certificate-bundle
        readOnly: true
```
