### ISSUE TITLE
Add `allowPrivilegeEscalation` to additional `securityContext` values

### ISSUE THREAD

**Issue by D1StrX** [netbox-community/netbox-chart#357]
In the Helm deployment values.yaml, I identified the following missing values in the `securityContext`;
- `init.securityContext.allowPrivilegeEscalation` -> `false`
- `test.securityContext.allowPrivilegeEscalation` -> `false`

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @D1StrX.
That said, I'm not sure to understand what your talking about.
`ephemeralContainers` is not part of the chart since months, and `securityContext`s are applied everywhere without all submitted parameters.
Could you be more specific and provide some references?

**Comment by D1StrX** [comment]
You can ignore the `ephemeralContainers` part. Seems to be fixed by the `securityContext` config described in the issue. Only the missing `securityContext` part is still relevant.

I identified some more stuff;
- The values for keys:values in `ingress.annotations` must be quoted. Otherwise I get the error ` json: cannot unmarshal number into Go struct field ObjectMeta.metadata.annotations of type string`.

- Even though my values define `replicas: 1` and `accessMode: ReadWriteOnce`, Netbox doesn't seem to work with RWO PVCs. `Multi-Attach error for volume <pvc> ... Volume is already used by pod(s) netbox-worker-xxxx`

**Comment by LeoColomb** [comment]
> Could you be more specific and provide some references?

Please.
What are the values you are using? What is the version of the chart? What is the output? What is instead expected? How to reproduce?

**Comment by D1StrX** [comment]
Netbox is being deployed by ArgoCD.

In the `values.yaml` allowPrivilegeEscalation is missing for `test` and `init`:
It's just a missing value for these specific, while the other securityContexts have them defined. In my testcase Kyverno policies got triggered.
```yaml
test:
...
  securityContext:
    enabled: false
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false      <--- This one
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
```

```yaml
init:
...
  securityContext:
    enabled: true
    seLinuxOptions: {}
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false      <--- This one
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
```

For `ingress` Helm values.yaml an example:
```yaml
ingress:
  enabled: true
  pathType: ImplementationSpecific
  className: "nginx"
  annotations:
    cert-manager.io/private-key-encoding: "PKCS8"
    cert-manager.io/private-key-size: "256"
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/24,192.168.1.0/24"
  hosts:
    - host: netbox.example.org
      paths:
        - /
  tls:
    - secretName: tls-netbox
      hosts:
        - netbox.example.org
 ```
 
 `cert-manager.io/private-key-size: 256` or `nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/24,192.168.1.0/24`, the values isn't quoted by the Chart itself.
 
**Chart version:** 5.0.0-beta.107 (same issue applies to 5.0.0-beta.105)
