### ISSUE TITLE
GKE storageClass Multi-Attach error

### ISSUE THREAD

**Issue by D1StrX** [netbox-community/netbox-chart#390]
### The Helm chart version

5.0.0-beta.112

### Environment Versions

```text
Kubernetes 1.29
GKE
```

### Custom chart values

```yaml
persistence:
  enabled: true
  storageClass: "rwo"
  subPath: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  existingClaim: ""
  annotations: {}
```

### Current Behavior & Steps to Reproduce

Regarding the storage behavior mentioned in https://github.com/netbox-community/netbox-chart/issues/357, I took a deeper look into the issue. Even RWO is an issue for us when your run a cluster with multiple K8s Worker nodes. The PVC, Netbox and Netbox-worker must reside on the same Worker node, otherwise you get `Multi-Attach error for volume <pvc> Volume is already used by pod(s) netbox-worker-xxx`. RWX isn't available on GKE, because `pd.csi.storage.gke.io` doesn't support it.

And why does Netbox-worker need access to Netbox-media?

### Expected Behavior

An alternative or perhaps improved documentation.
