### ISSUE TITLE
StorageBackends not working with GoogleCloudStorage

### ISSUE THREAD

**Issue by pimvandenbroek** [netbox-community/netbox-chart#394]
### The Helm chart version

netbox-5.0.0-beta.132

### Environment Versions

```text
Kubernetes 1.29
GKE
```

### Custom chart values

```yaml
# Use Google Cloud Storage backend
storageBackend: storages.backends.gcloud.GoogleCloudStorage
# Provide the necessary configuration for GCS
storageConfig:
  GS_BUCKET_NAME: 'your-gcs-bucket-name'
  GOOGLE_APPLICATION_CREDENTIALS: '/path/to/your/credentials.json'
```

### Current Behavior & Steps to Reproduce

- Create a storage bucket
- Create a serviceaccount
- Mount the serviceaccount in the deployment to '/path/to/your/credentials.json'
- Add the config above

When uploading a file, you'll get:
```
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'google.api_core.exceptions.Forbidden'>

403 POST https://storage.googleapis.com/upload/storage/v1/b/your-gcs-bucket-name/o?uploadType=multipart: {
  "error": {
    "code": 403,
    "message": "Access denied.",
    "errors": [
      {
        "message": "Access denied.",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
: ('Request failed with status code', 403, 'Expected one of', <HTTPStatus.OK: 200>)

Python version: 3.12.3
NetBox version: 4.1.4
Plugins: None installed
If further assistance is required, please post to the NetBox discussion forum on GitHub.
```

 

### Expected Behavior

I expect that files were uploaded to GCS.

Multiple tests were done:
- Local test using export GOOGLE_APPLICATION_CREDENTIALS='/path/to/your/credentials.json', and then using google.cloud python package to upload a file. This worked fine
- Jumped into the netbox-pod, and did the same. This also worked fine
- Created a django app, purely for uploading a file to gcloud storage. I had to add `GOOGLE_APPLICATION_CREDENTIALS` instead of `GS_CREDENTIALS`. After that file upload worked perfectly.
