### ISSUE TITLE
Render extraEnvs so it can be configured with templated values

### ISSUE THREAD

**Issue by NeodymiumFerBore** [netbox-community/netbox-chart#403]
### Proposed functionality

Render the `.Values.extraEnvs` list so we can use templated values in it.

### Use case

This feature would solve the issue exposed in this example Values. When deploying "extra" resources, we cannot reference their name in `extraEnvs` by using the templated form.

```yaml
extraDeploy:
- |
  apiVersion: v1
  kind: Secret
  metadata:
    # templated name, for multi-env portability
    name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "extra-env" "context" $) }}
    labels: {} # omitted
  type: Opaque
  data:
    CUSTOM_SECRET: {{ .Values.CUSTOM_SECRET | b64enc | quote }}

# This would be set from command line
CUSTOM_SECRET: mySuperPassword

extraEnvs:
- name: CUSTOM_SECRET
  valueFrom:
    secretKeyRef:
      name: how do we reference it without hardcoding the Release name here?
      key: CUSTOM_SECRET
```

This problem can be worked around by variabilizing the secret name, but then we must "not forget" to update it from an environment to another. Implementing this feature request would allow to write:

```yaml
extraEnvs:
- name: CUSTOM_SECRET
  valueFrom:
    secretKeyRef:
      name: '{{ include "common.secrets.name" (dict "defaultNameSuffix" "extra-env" "context" $) }}'
      key: CUSTOM_SECRET
```
