### ISSUE TITLE
Support Postgresql `sslrootcert` option

### ISSUE THREAD

**Issue by joachimBurket** [netbox-community/netbox-chart#417]
### Proposed functionality

Add the value `externalDatabase.sslRootCert`, and put it in the `configuration.py`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  # [ ... ]
data:
  configuration.py: |-
    {{ .Files.Get "files/configuration.py" | nindent 4 }}

  netbox.yaml: |-
    # [ ... ]

    DATABASE:
      # [ ... ]      
      OPTIONS:
        sslmode: {{ .Values.externalDatabase.sslMode | quote }}
        
        # add the options here
        sslrootcert: {{ .Values.externalDatabase.sslRootCert | quote }}

      # [ ... ]
```

Maybe the `externalDatabase.sslRootCert` value could be set to `system` by default, but it could be a breaking change because by default my container tries to get the CA cert from `//.postgresql/root.crt`

### Use case

When setting the value `externalDatabase.sslMode` to `verify-full`, it should be possible to configure the path of the CA bundle (or set it to `system` to use the system CA bundle)
