### ISSUE TITLE
LDAP INVALID_DN_SYNTAX

### ISSUE THREAD

**Issue by bl4ko** [netbox-community/netbox-chart#427]
### The Helm chart version

netbox-5.0.0-beta9

### Environment Versions

```text
Kubernetes: v1.30.5
Helm: v3.16.1
```

### Custom chart values

```yaml
remoteAuth:
  enabled: true
  backends:
  - netbox.authentication.LDAPBackend
  ldap:
    serverUri: "ldaps://srcljdc1.src.si"
    startTls: false
    ignoreCertErrors: true
    bindDn: "CN=provisioner,OU=services,DC=example,DC=com"
    userSearchAttr: "sAMAccountName"
    userSearchBaseDn: "DC=example,DC=com"
    groupSearchBaseDn: "DC=example,DC=com"
    findGroupPerms: false
    userDnTemplate: null
    groupSearchClass: "top"
    groupType: "GroupOfNamesType"
    requireGroupDn:
      - 'CN=operacije,OU=example-groups,DC=example,DC=com'
      - 'CN=admins,OU=Administrators,OU=example-groups,DC=example,DC=com'
    isAdminDn:
      - 'CN=admins,OU=Administrators,OU=example-groups,DC=example,DC=com'
    isSuperUserDn:
      - 'CN=admins,OU=Administrators,OU=example-groups,DC=example,DC=com'
    mirrorGroups: null
    mirrorGroupsExcept: null
    cacheTimeout: 3600
    attrFirstName: "givenName"
    attrLastName: "sn"
    attrMail: "mail"
```

### Current Behavior & Steps to Reproduce

The same configuration worked with [29d4598683696a476234618b73732d8b17424834](https://github.com/netbox-community/netbox-chart/commit/29d4598683696a476234618b73732d8b17424834). But after that something was changed.

### Expected Behavior

LDAP works normally with this configuration.

### NetBox Logs

```text
Binding as cn=adm user,ou=admins,dc=example,dc=com
Binding as CN=provision,OU=services,DC=example,dc=com
Caught LDAPError while authenticating admuser: INVALID_DN_SYNTAX({'msgtype': 111, 'msgid': 3, 'result': 34, 'desc': 'Invalid DN syntax', 'ctrls': [], 'info': "0000208F: NameErr: DSID-03100232, problem 2006 (BAD_NAME), data 8349, best match of:\n\t'[cn=operacije,ou=example-groups,DC=example,dc=com CN=admins,ou=administrators,ou=example-groups,DC=example,dc=com]'\n"})
10.42.79.164 - - [03/Dec/2024:11:51:05 +0000] "POST /login/ HTTP/1.1" 200 4381 "https://netbox.test-rke2-cluster.example.com/login/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
```
