### ISSUE TITLE
PostgreSQL and Redis `existingSecret` not respected on ArgoCD sync

### ISSUE THREAD

**Issue by salcinad** [netbox-community/netbox-chart#450]
### The Helm chart version

5.0.0-beta.167

### Environment Versions

```text
Kubernetes: 1.28.8
ArgoCD: v2.13.0+347f221
```

### Custom chart values

```yaml
        superuser:
          name: admin
          email: example@example.com
          existingSecret: "netbox-superuser"
        existingSecret: "netbox-config"
        postgresql:
          auth:
            existingSecret: "netbox-postgresql"
            secretKeys:
              adminPasswordKey: "postgres-password"
              userPasswordKey: "password"
        redis:
          auth:
            existingSecret: "netbox-redis"
            existingSecretPasswordKey: "redis-password"
```

### Current Behavior & Steps to Reproduce

Tested with different option in valuey.yaml for existing secrets but did it just do not work. Once the secret is overwritten, the worker complains that password is incorrect, and the whole netbox pod does not start.
`django.db.utils.OperationalError: connection failed: connection to server at "10.95.18.196", port 5432 failed: FATAL:  password authentication failed for user "netbox"`

Even if we do not use existingSecrets and let ArgoCD create secrets, they are getting regenerated over every ArgoCD sync. No issue with other applications.

### Expected Behavior

The existingSecrets should not be overwriten by netbox chart.

### NetBox Logs

```text
Not an NetBox issue.
```

**Comment by LeoColomb** [comment]
Thanks for your input.
I'm going a little ahead and suggest some potential root causes.
* If you first generate secret with the chart and _then_ reference them with `existingSecret`, this will not work: generated secrets will not be rendered anymore and thus not kept in the cluster, previous version will be deleted.
* If using auto-management inherited from the chart is not working as expected (i.e. passwords are not kept between upgrade/sync, which is surprising already but might happen), then you must declare _first_ the secrets manually before referencing them into the values.

**Comment by salcinad** [comment]
> * If you first generate secret with the chart and _then_ reference them with `existingSecret`, this will not work: generated secrets will not be rendered anymore and thus not kept in the cluster, previous version will be deleted.

This is how we did Initial setup, we let chart deploy without setting existingSecret or setting passwords manually. then exported these secrets to yaml, deleted unneeded data from yaml (see below), deleted application, deleted namespace where it was installed, used then existingSecret to reference to these secrets exported yaml, and added them to values.yaml under `extraDeploy` , updated ArgoCD Application.
```
$ cat netbox-postgresql-dev.yaml
apiVersion: v1
data:
  password: bXB5bXSd05TVlid05TRQ==
  postgres-password: WG40FpbSlW9YWG40TQ==
kind: Secret
metadata:
  name: netbox-postgresql
  namespace: netbox
type: Opaque

$ cat netbox-redis-dev.yaml
apiVersion: v1
data:
  redis-password: TKZGbjVMW2mpQQ==
kind: Secret
metadata:
  name: netbox-redis
  namespace: netbox
type: Opaque

$
```


In my [comment ](https://github.com/netbox-community/netbox-chart/issues/450#issuecomment-2546462322) above the application deployed successfully, the ArgoCD deployed sealed-secrets which are applied to correct namespace in correct k8s cluster and NetBox is available over Ingress and login (superuser - which is also existing secret) its working just fine, all pods up (see below), as well as LDAPs.
```
$ k get pods -n netbox
NAME                                 READY   STATUS      RESTARTS      AGE
netbox-869547468c-6mdqv              1/1     Running     5 (9h ago)    10h
netbox-housekeeping-28906560-qnc9v   0/1     Completed   0             7h6m
netbox-postgresql-0                  1/1     Running     0             10h
netbox-redis-master-0                1/1     Running     0             10h
netbox-redis-replicas-0              1/1     Running     0             10h
netbox-redis-replicas-1              1/1     Running     0             10h
netbox-redis-replicas-2              1/1     Running     0             10h
netbox-worker-7cc9d556d7-5pffx       1/1     Running     2 (10h ago)   10h
$
```

But now ArgoCD is showing that this Application is `OutOfSync`, as there are these two secret which we did not sync in fist name. We also checked the secret in namespace with password in yaml files and are identical.
This is somehow weird, but we are out of Ideas what could be wrong.

![grafik](https://github.com/user-attachments/assets/db9f59c2-73b3-4541-a5dc-dd0faf946699)

**Comment by LeoColomb** [comment]
Thanks for the details. 
Can you try following the same procedure but changing the name of the manual secrets?
1. Raw install 
2. Secrets exports
3. Clear labels and change the name (e.g. with `-2` prefix)
4. Add `existingSecret` with the new names 

If this still does not work, can you confirm the secrets values do not get base64 encoded twice?

**Comment by Delta1977** [comment]
if i read  right in first row of secret template ( {{- if not .Values.existingSecret }}) 
all Secrets were autorendered when existing secret is not set.

**Comment by LeoColomb** [comment]
@Delta1977 Not all secrets, each secret has its own condition to be rendered. 
In any case, the secrets template in NetBox chart has nothing in relation with bundled Bitnami charts (ProsgreSQL / Redis).

**Comment by salcinad** [comment]
> Thanks for the details. Can you try following the same procedure but changing the name of the manual secrets?
> 
>     1. Raw install
> 
>     2. Secrets exports
> 
>     3. Clear labels and change the name (e.g. with `-2` prefix)
> 
>     4. Add `existingSecret` with the new names
> 
> 
> If this still does not work, can you confirm the secrets values do not get base64 encoded twice?

I did deployed yesterday with helm only and without changing anything just did helm upgrade, when comparing what changed with helm-diff plugin, i see that checksum is different for redis
```
$ previous_release="$(helm history -n netbox-dev netbox | tail -2 | head -1 | cut -f 1 -d' ')"
$ helm diff -n netbox-dev revision netbox "$previous_release"
```

```
netbox-dev, netbox-config, Secret (v1) has changed:
..
    email_password: 'REDACTED # (0 bytes)'
-   secret_key: '-------- # (60 bytes)'
+   secret_key: '++++++++ # (60 bytes)'

...
netbox-dev, netbox-redis-master, StatefulSet (apps) has changed:
..
-         checksum/secret: 7baef362ee982134ba8753456e11074766c9757df9fdd3edf991c121b98d09c2
+         checksum/secret: a9c6331012a7379282f97f715c4e18b77794d282502dbe19cb86b2837279e586

...
netbox-dev, netbox-redis-replicas, StatefulSet (apps) has changed:
..
-         checksum/secret: bc3c09cdec721b1bb1288642521702ab3cec072e6d8e1905937ae067c8449ea8
+         checksum/secret: a9c6331012a7379282f97f715c4e18b77794d282502dbe19cb86b2837279e586

..

netbox-dev, netbox-superuser, Secret (v1) has changed:
..
-   api_token: '-------- # (36 bytes)'
+   api_token: '++++++++ # (36 bytes)'
    email: 'REDACTED # (18 bytes)'
    password: 'REDACTED # (10 bytes)'
    username: 'REDACTED # (5 bytes)'

...
```


I am checking that with point 3. from your recommendation.

**Comment by LeoColomb** [comment]
@salcinad Thanks for your replies, but I'm afraid none of this makes sense.
Everything is pointing to a misconfiguration on your side, though, and the only possible last step would be dumping your complete `values.yaml` and the output of a `helm template` with these values.
Could you do this into a Gist or similar?

**Comment by LeoColomb** [comment]
Thank you for your reply, @salcinad.
I'm afraid, again, it's nearly impossible to extract any valuable information from this to diagnostic and provide support.
This helm chart is reaching 10k installations, and your report only so far about this fundamental problem…
Everything is pointing to a misconfiguration on your side, though, and the only possible last step would be dumping your complete `values.yaml` and the output of a `helm template` with these values.
Could you do this into a Gist or similar?

**Comment by Delta1977** [comment]
I have the same Problem with this Chart and ArgoCD so @salcinad is not alone

**Comment by mnorrsken** [comment]
I've gone through my charts and it seems most of the ones creating random passwords in secrets are using helm hooks to either only create the secret on initial install, or to spin up a job that goes through and updates secrets if needed. There's also a "lookup" functionality in helm that could be used to preserve passwords, but I've yet to find a chart (in my cluster) actually using this feature.

If this gets annoying enough I will try the helm hooks and create a PR.

**Comment by geilername** [comment]
I dont think helm hooks and lookup are of any use here as we are talking about deploying with argocd and using existingSecrets, the existingSecrets just need to be honored, somehow it feels like passing down configuration to the subcharts doesnt work correctly here

**Comment by mnorrsken** [comment]
You are correct, something else is going on here. Looking at the secret.yaml template, I realize that the netbox-config secret is never out of sync in this manner.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "superuser" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.superuser.name | default "admin" | b64enc | quote }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.secrets.name" (dict "defaultNameSuffix" "superuser" "context" $)) "key" "password" "providedValues" (list "superuser.password") "context" $) }}
  email: {{ .Values.superuser.email | b64enc | quote }}
  api_token: {{ .Values.superuser.apiToken | default uuidv4 | b64enc | quote }}
{{- end }}
{{- if not (or .Values.postgresql.enabled .Values.externalDatabase.existingSecretName) }}
```

Looking at this code there are three things that differs this secret from netbox-config that may trigger a "diff"
* type: kubernetes.io/basic-auth
* The calling of a subchart to render the password
* using uuidv4 instead of a rand function for api_token

I will try to play around with these things and check what happens.

**Comment by LeoColomb** [comment]
Thanks all for your replies.
To provide support, please allow me to ask some questions.

> Only this chart exhibiting this issue.

Do you have any example of another chart **with Bitnami's charts as dependencies** that is working without issue? @mnorrsken 

> There's also a "lookup" functionality in helm that could be used to preserve passwords

It is actively used anywhere the helper `common.secrets.passwords.manage` is called.

> Looking at the secret.yaml template

Please note that `secret.yaml` is completely independent of Bitnami sub-chart (PostgreSQL / Redis in here).

---

As requested before in this issue, it would be nice to get a complete set of custom values / ArgoCD values + fully rendered helm templates.

**Comment by geilername** [comment]
I just found the error in @salcinad config.

postgresql and redis where duplicates in the values file so the existingSecret keys where not honored
```yaml
postgresql:
  auth:
    existingSecret: "netbox-postgresql"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
redis:
  auth:
    existingSecret: "netbox-redis"
    existingSecretPasswordKey: "redis-password"
----
truncated
----
postgresql:
  image:
    registry: harbor.xxxxxxx.at/cache
redis:
  image:
    registry: harbor.xxxxxxx.at/cache
```
instead of
```yaml
postgresql:
  auth:
    existingSecret: "netbox-postgresql"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
  image:
    registry: harbor.xxxxxxx.at/cache
redis:
  auth:
    existingSecret: "netbox-redis"
    existingSecretPasswordKey: "redis-password"
  image:
    registry: harbor.xxxxxxx.at/cache
```

so the issue was indeed in the values file, maybe the others have the same error in their values.
