### ISSUE TITLE
Usage of `ISOLATED_DEPLOYMENT`

### ISSUE THREAD

**Issue by alihoda** [netbox-community/netbox-chart#464]
### Proposed functionality

It seems that netbox v4.1.x can use a system parameter called `ISOLATED_DEPLOYMENT`, but I can not find it in the netbox helm chart.

### Use case

For deployment environment where there is no internet connection, RSS feed panel in netbox dashboard cause delay in dashboard loading time.

**Comment by salcinad** [comment]
This is also something we are looking for. I tried an different way to disable this but I am unable to deploy netbox at all if do something like written [helm chart - change default dashboard - disable RSSFeedWidget #18216](https://github.com/netbox-community/netbox/discussions/18216)

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @alihoda.
You can add any additional NetBox parameters using the values `extraConfig`.
For instance:
```yaml
extraConfig:
  - values:
      ISOLATED_DEPLOYMENT: true
```

If you feel it's relevant to actually add this option explicitly in the chart, don't hesitate to open a pull request with this addition.

---
@salcinad Your use case is correct, you simply need to be careful about the `extraConfig` templating. The extra config is expected to be provided as a valid YAML.
For example:
```yaml
extraConfig:
  - values:
      DEFAULT_DASHBOARD:
        - {}
```
