### ISSUE TITLE
Unable to install Chart due to misconfigured LDAP values validation

### ISSUE THREAD

**Issue by 0xmeyer** [netbox-community/netbox-chart#508]
### The Helm chart version

5.0.21

### Environment Versions

```text
Kubernetes 1.29
Helm 3.14
```

### Custom chart values

```yaml
remoteAuth:
  enabled: true
  backends:
    - netbox.authentication.LDAPBackend
[...]
  ldap:
    serverUri: "ldaps://ldap.example.com"
    startTls: false
    ignoreCertErrors: false
    caCertDir: ""
    caCertData: ""
    bindDn: ""
    bindPassword: ""
```

### Current Behavior & Steps to Reproduce

* Netbox ` v4.1.3`
* Netbox chart `4.1.1`

We would like to migrate to the `5.0.21` chart, but the values validation of the LDAP values is not correct. Currently both values `.Values.remoteAuth.ldap.serverUri` and `.Values.remoteAuth.ldap.bindDn` have to be set so that the Helm Chart is installed and you don't get the error message “When LDAP backend is activated, you must provide all the necessary parameters”. 

```
Pulled: ghcr.io/netbox-community/netbox-chart/netbox:5.0.21
Digest: sha256:60518a70156a40b6d830571711237889b228c2f1c9824abbf19a49c330d51ac2
Error: UPGRADE FAILED: execution error at (netbox/templates/NOTES.txt:51:4): 
VALUES VALIDATION:
netbox: remoteAuth.ldap
    When LDAP backend is activated, you must provide all the necessary parameters.
    Review the values under `remoteAuth.ldap`.
```

### Expected Behavior

It should be possible to specify `.Values.remoteAuth.ldap.serverUri`  without  `.Values.remoteAuth.ldap.bindDn`.

```diff
diff --git a/charts/netbox/templates/_helpers.tpl b/charts/netbox/templates/_helpers.tpl
index fa90f9f..ebd7a26 100644
--- a/charts/netbox/templates/_helpers.tpl
+++ b/charts/netbox/templates/_helpers.tpl
@@ -174,7 +174,7 @@ netbox: postgresql
 Validate values of Netbox Chart - LDAP
 */}}
 {{- define "netbox.validateValues.ldap" -}}
-{{- if and (has "netbox.authentication.LDAPBackend" .Values.remoteAuth.backends) (or (empty .Values.remoteAuth.ldap.serverUri) (empty .Values.remoteAuth.ldap.bindDn)) -}}
+{{- if and (has "netbox.authentication.LDAPBackend" .Values.remoteAuth.backends) (and (empty .Values.remoteAuth.ldap.serverUri) (empty .Values.remoteAuth.ldap.bindDn)) -}}
 netbox: remoteAuth.ldap
     When LDAP backend is activated, you must provide all the necessary parameters.
     Review the values under `remoteAuth.ldap`.
```

### NetBox Logs

```text

```
