### ISSUE TITLE
Allow existing secret to set/supply the global.redis.password value

### ISSUE THREAD

**Issue by diepes** [netbox-community/netbox-chart#517]
### The Helm chart version

netbox-5.0.22

### Environment Versions

```text
Kubernetes: v1.30.4
```

### Custom chart values

```yaml
global:
  redis:
    existingSecretName: "private-secrets"
    existingSecretKey: redis-password
```

### Current Behavior & Steps to Reproduce

I tried to deploy the helm chart a 2nd time using bitbucket pipeline and got the error ....

```
Error: UPGRADE FAILED: execution error at (netbox/charts/redis/templates/replicas/application.yaml:52:35): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
    'global.redis.password' must not be empty, please add '--set global.redis.password=$REDIS_PASSWORD' to the command. To get the current value:
```

There is the option to set custom secrets for other values why not for global.redis.password ?
This did not work.

```
global:
  redis:
    existingSecretName: "private-secrets"
    existingSecretKey: redis-password
```

### Expected Behavior

I expect that when i deploy/redeploy the netbox helm chart, all values should be provisioned through values.yaml and a pre-existing secret with the required values.

### NetBox Logs

```text

```

**Comment by salcinad** [comment]
I [used this](https://github.com/netbox-community/netbox-chart/issues/450#issuecomment-2607355827) on our side to set existingSecret, but this was with embeded redis, not the external one, not sure what is on your side, but I guess it should be same.

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @diepes.
Reading your report, I assume you're using the bundled Bitnami Redis deployment.
For "bundled" Bitnami PostgreSQL/Redis charts, all the upstream values can be used accordingly, in their respective namespace.
For instance:
* PostgreSQL: `postgresql.auth.existingSecret`, see https://artifacthub.io/packages/helm/bitnami/postgresql
* Redis: `redis.auth.existingSecret`, see https://artifacthub.io/packages/helm/bitnami/redis

**Comment by diepes** [comment]
Thanks @LeoColomb and @salcinad for the advice.

Ok i think i understand better now, in the sub charts configured under "redis:" or "postresql:" i have to look at the specific chart docs/configs and there they use "existingSecret:" to refer to secrets but in the netbox chart i should use "existingSecretName:" to use secrets.

To check i understand correctly, i create a secret e.g. "my-secrets" with keys, then i use the 
In values.yaml
```
global:
  ...
redis:
  enabled: true
  auth:
    existingSecret: "my-secrets"
    existingSecretPasswordKey: "redis-password"

tasksRedis:
   ...
  existingSecretName: "my-secret"
  existingSecretKey: redis-password

postgresql:
  enabled: false

externalDatabase:
  ...
  username: psqluser
  existingSecretName: "my-secrets"
  existingSecretKey: postgresql-password
  ...
```

Thanks for the guidance.
