### ISSUE TITLE
ISOLATED_DEPLOYMENT active only on first page

### ISSUE THREAD

**Issue by salcinad** [netbox-community/netbox-chart#518]
### The Helm chart version

netbox-5.0.22

### Environment Versions

```text
Kubernetes: 1.28.8
Argo CD: v2.13.3+a25c8a0
```

### Custom chart values

```yaml
        extraConfig:
          - values:
              ISOLATED_DEPLOYMENT: true
```

### Current Behavior & Steps to Reproduce

As discussed in Issue #464 (but seems as closed, my comment got lost) seems this ISOLATED_DEPLOYMENT is active only on front page and not after login.

### Expected Behavior

ISOLATED_DEPLOYMENT active for whole deployment and not just front page. See Issue #464 and my [comment ](https://github.com/netbox-community/netbox-chart/issues/464#issuecomment-2609704619)

### NetBox Logs

```text

```
