### ISSUE TITLE
Feature Request: Add support for sleep in the deployments preStop lifecycle hook, to allow for seamless deployments

### ISSUE THREAD

**Issue by mimukr** [netbox-community/netbox-chart#528]
### Proposed functionality

The proposed functionality would add something like the following option to `charts/netbox/templates/deployment.yaml` within `spec.template.spec.containers`:

```yaml
{{- if .Values.preStopSleep }}
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "sleep {{ .Values.preStopSleep }}"]
{{- end }}
```
Example: `preStopSleep: 15`

or alternatively, to allow for more customization:

```yaml
{{- if .Values.preStopCommand }}
lifecycle:
  preStop:
    exec:
      command: {{ $instance.preStopCommand | toJson }}
{{- end }}
```
Example: `preStopCommand: ["/bin/sh", "-c", "sleep 15"]`

### Use case

We are deploying the Helm chart using AWS EKS and using an AWS Application Load Balancer for the Ingress. Unfortunately, during our deployment, there seems to be a delay between the service endpoint change at the cluster level and the corresponding change in AWS. This means that traffic will still be routed to the old instance for some seconds after Kubernetes has started terminating it, resulting in temporary downtime.

The above solution will have the old instance respond to requests for a couple of extra seconds, alleviating this issue and allowing for seamless deployments. Other load balancers or setups might have the same issue and likewise find this useful.
