### ISSUE TITLE
Persistence Annotations are not added to the PVC

### ISSUE THREAD

**Issue by waza-ari** [netbox-community/netbox-chart#538]
### The Helm chart version

5.0.31

### Environment Versions

```text
Kubernetes 1.31
```

### Custom chart values

```yaml
"persistence":
  "accessMode": "ReadWriteMany"
  "annotations":
    "k8up.io/backup": "true"
  "enabled": true
  "size": "10Gi"
  "storageClass": "ceph-fs"
```

### Current Behavior & Steps to Reproduce

This should add the specified annotation to the PVC, the parameter `persistence.annotations` is not referenced in the chart though.

### Expected Behavior

The annotation should be added to the PVC.
