### ISSUE TITLE
Allow `DEFAULT_DASHBOARD` configuration

### ISSUE THREAD

**Issue by abhi1693** [netbox-community/netbox-chart#575]
### Proposed functionality

Allow [`DEFAULT_DASHBOARD`](https://netboxlabs.com/docs/netbox/en/stable/configuration/default-values/#default_dashboard) in values.yaml

### Use case

Easy access to update config during deployment

**Comment by LeoColomb** [comment]
Thanks for filing this issue, @abhi1693.
For any additional NetBox configuration setting, it's recommended to use the extra configuration value (`extraConfig`).
For example, the following snippet should be sufficient:

```yaml
extraConfig:
  - values:
      DEFAULT_DASHBOARD: [{
        'widget': 'extras.ObjectCountsWidget',
        ...
      }]
```
