### ISSUE TITLE
Netbox chart gives 'gzip encoding' error with Flux helm controller

### ISSUE THREAD

**Issue by rossigee** [netbox-community/netbox-chart#613]
### The Helm chart version

netbox-5.0.x

### Environment Versions

```text
Kubernetes: 1.32.2
FluxCD: latest
```

### Custom chart values

```yaml
N/A - see below
```

### Current Behavior & Steps to Reproduce

When adding the `netbox` Helm chart to a Flux2 deployment, there is an error due to the format of the OCI file being generated...

```
failed to extract layer contents from artifact: requires gzip-compressed body: gzip: invalid header   33s
```

Steps to reproduce...

```
minikube start --profile=netbox-chart-test
curl -s https://fluxcd.io/install.sh | sudo bash
flux install
```
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbox
spec:
  interval: 12h
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
  ref:
    semver: "^5.x.x"
```
```
kubectl apply -f netbox-repo.yaml
...
kubectl get ocirepository netbox
```

gives...

```
NAME     URL                                                  READY   STATUS                                                                                                AGE
netbox   oci://ghcr.io/netbox-community/netbox-chart/netbox   False   failed to extract layer contents from artifact: requires gzip-compressed body: gzip: invalid header   33s
```

### Expected Behavior

The expected behaviour should be as per the `netbox-operator` chart, which works fine...

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbox-operator
spec:
  interval: 12h
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox-operator
  ref:
    semver: "^0.x.x"
```
```
kubectl apply -f netbox-operator-repo.yaml
...
kubectl get ocirepository netbox-operator
```

Gives...

```
NAME              URL                                                           READY   STATUS                                                                                                        AGE
netbox-operator   oci://ghcr.io/netbox-community/netbox-chart/netbox-operator   True    stored artifact for digest '0.3.25@sha256:f2c2890304d72f3a490bd45faeb655d9c634948d4a22ac140421c32e7d490a71'   2m1s
...

```

### NetBox Logs

```text

```
