### ISSUE TITLE
It is required that i use groups for ldap authentification

### ISSUE THREAD

**Issue by fga1794** [netbox-community/netbox-chart#637]
### The Helm chart version

netbox-5.0.24

### Environment Versions

```text
kubernetes
```

### Custom chart values

```yaml
remoteAuth:
  enabled: false
  backends:
    - netbox.authentication.LDAPBackend
  autoCreateUser: true
  header: HTTP_REMOTE_USER
  ldap:
    serverUri: 'xx'
    startTls: true
    ignoreCertErrors: true
    bindDn: "xx" 
    bindPassword: ldap_bind_password
    # userDnTemplate: ""
    userSearchBaseDn: "xx"
    userSearchAttr: sAMAccountName
```

### Current Behavior & Steps to Reproduce

Hello, i don't want to use the groups for authentification ldap
https://netboxlabs.com/docs/netbox/en/stable/installation/6-ldap/

However, the file created by helm use groups. If i do not put values , it set default one and does not work
How can i do without groups ?

### Expected Behavior

use ldap only with search user without group associted to AD

### NetBox Logs

```text

```
