### ISSUE TITLE
Setting superuser role based on Keycloak role

### ISSUE THREAD

**Issue by AsilBouni** [netbox-community/netbox-chart#702]
### The Helm chart version

Chart: 5.0.1

### Environment Versions

```text
Netbox: 4.2.3
```

### Custom chart values

```yaml
remoteAuth:
    enabled: true
    backends:
      - social_core.backends.keycloak.KeycloakOAuth2
      - django.contrib.auth.backends.ModelBackend
    autoCreateUser: true
 
  extraConfig:
    - secret:
        secretName: keycloak-client
    - values:
        SOCIAL_AUTH_PIPELINE:
          [
            "social_core.pipeline.social_auth.social_details",
            "social_core.pipeline.social_auth.social_uid",
            "social_core.pipeline.social_auth.social_user",
            "social_core.pipeline.user.get_username",
            "social_core.pipeline.social_auth.associate_by_email",
            "social_core.pipeline.user.create_user",
            "social_core.pipeline.social_auth.associate_user",
            "netbox.authentication.user_default_groups_handler",
            "social_core.pipeline.social_auth.load_extra_data",
            "social_core.pipeline.user.user_details",
            "netbox.sso_pipeline_roles.set_role",
          ]
 
  extraVolumes:
    - name: sso-pipeline-roles
      configMap:
        name: sso-pipeline-roles
 
  extraVolumeMounts:
    - name: sso-pipeline-roles
      mountPath: /opt/netbox/netbox/netbox/sso_pipeline_roles.py
      subPath: sso_pipeline_roles.py
      readOnly: true



   extraDeploy:
     - |yaml
       apiVersion: v1
       kind: ConfigMap
       metadata:
         name: sso-pipeline-roles
         namespace: netbox-dev
       data:
         sso_pipeline_roles.py: |py
           from django.conf import settings
           from netbox.authentication import Group
  
           def set_role(response, user, backend, *args, **kwargs):
             client_id = getattr(settings, 'SOCIAL_AUTH_KEYCLOAK_KEY', None)
             staff_role = getattr(settings, 'SOCIAL_AUTH_STAFF_ROLE', 'staff')
             superuser_role = getattr(settings, 'SOCIAL_AUTH_SUPERUSER_ROLE', 'superuser')
  
             roles = []
             try:
               roles = response['resource_access'][client_id]['roles']
             except KeyError:
               pass
             user.is_staff = (staff_role in roles)
             user.is_superuser = (superuser_role in roles)
             user.save()
             groups = Group.objects.all()
             for group in groups:
               try:
                 if group.name in roles:
                   group.users.add(user)
                 else:
                   group.users.remove(user)
               except Group.DoesNotExist:
                 continue
```

### Current Behavior & Steps to Reproduce

Using the [documentation](https://github.com/netbox-community/netbox-chart/blob/main/charts/netbox/docs/auth.md) this Github repo provides, i tried configuring automated role assignment for users.

My current configuration allows users to successfully sign in using SSO with Keycloak as backend. But users that are assigned the admin role in keycloak (which corresponds with the value of SOCIAL_AUTH_SUPERUSER_ROLE) don't become superusers.

When checking out the access token I can clearly see that the user is assigned the correct resource access value:
  "resource_access": {
    "netbox-dev": {
      "roles": [
        "netbox-dev-administrators"
      ]
    }

I already verified that all secrets used in my configuration are correct but still no succes.

### Expected Behavior

I would expect that whoever is assigned the netbox-dev-administrators role in Keycloak automatically becomes superuser in Netbox.

### NetBox Logs

```text

```
