### ISSUE TITLE
Secret issues when not using valkey on the netbox chart

### ISSUE THREAD

**Issue by christiaangoossens** [netbox-community/netbox-chart#709]
### The Helm chart version

netbox:6.0.22

### Environment Versions

```text
-
```

### Custom chart values

```yaml
valkey:
  enabled: false

tasksDatabase:
  host: netbox-redis

cachingDatabase:
  host: netbox-redis
```

### Current Behavior & Steps to Reproduce

1. Provided config doesn't work, because the chart requires the secret `netbox-valkey` to exist and the containers don't init otherwise
2. Change the config to include:

```
valkey:
  enabled: false

tasksDatabase:
  host: netbox-redis
  existingSecretName: "netbox-kv"
  existingSecretKey: tasks_password

cachingDatabase:
  host: netbox-redis
  existingSecretName: "netbox-kv"
  existingSecretKey: cache_password
```

And then create a secret `netbox-kv` (like there used to be) with two empty values, and it works fine.

### Expected Behavior

It should not require that `netbox-valkey` secret to exist if no passwords are specified and valkey is disabled.

### NetBox Logs

```text

```
